---
driver:
  name: docker
  hostname: packages-formula.ci.local
  use_sudo: false
  privileged: true

provisioner:
  name: salt_solo
  # No need for chef as we're not using busser
  require_chef: false
  formula: packages
  pillars-from-files:
    packages.sls: pillar.example
  pillars:
    top.sls:
      base:
        '*':
          - packages
  state_top:
    base:
      '*':
        - packages

platforms:
  - name: debian-8
  - name: debian-9
  - name: centos-6
  - name: centos-7

suites:
  - name: packages-present
    provisioner:
      state_top:
        base:
          '*':
            - packages
  - name: packages-absent
    provisioner:
      state_top:
        base:
          '*':
            - packages

verifier:
  name: shell
  remote_exec: false
  # Command changed to allow running the same tests with different parameters
  command: py.test --connection=docker --hosts=root@$KITCHEN_CONTAINER_ID --junit-xml junit-$KITCHEN_INSTANCE.xml test/integration/$(echo $KITCHEN_SUITE | sed 's/_.*//')
