language: ruby

sudo: required

services:
  - docker

# https://github.com/zuazo/kitchen-in-travis-native/issues/1#issuecomment-142455888
before_script: sudo iptables -L DOCKER || sudo iptables -N DOCKER

before_install:
  # Installing testinfra and requirements
  - sudo pip install -r requirements.txt

script: bundle exec kitchen verify

